# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(493, 416)
        self.inputImage = QtWidgets.QLabel(Dialog)
        self.inputImage.setGeometry(QtCore.QRect(20, 20, 201, 171))
        self.inputImage.setObjectName("inputImage")
        self.selectImage = QtWidgets.QPushButton(Dialog)
        self.selectImage.setGeometry(QtCore.QRect(20, 220, 75, 23))
        self.selectImage.setObjectName("selectImage")
        self.predictImage = QtWidgets.QPushButton(Dialog)
        self.predictImage.setGeometry(QtCore.QRect(140, 220, 75, 23))
        self.predictImage.setObjectName("predictImage")
        self.outputImage = QtWidgets.QLabel(Dialog)
        self.outputImage.setGeometry(QtCore.QRect(260, 20, 201, 171))
        self.outputImage.setObjectName("outputImage")
        self.textEdit1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit1.setEnabled(False)
        self.textEdit1.setGeometry(QtCore.QRect(20, 260, 461, 21))
        self.textEdit1.setObjectName("textEdit1")
        self.textEdit2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit2.setEnabled(False)
        self.textEdit2.setGeometry(QtCore.QRect(20, 290, 461, 21))
        self.textEdit2.setObjectName("textEdit2")
        self.textEdit3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit3.setEnabled(False)
        self.textEdit3.setGeometry(QtCore.QRect(20, 320, 461, 21))
        self.textEdit3.setObjectName("textEdit3")
        self.textEdit4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit4.setEnabled(False)
        self.textEdit4.setGeometry(QtCore.QRect(20, 350, 461, 21))
        self.textEdit4.setObjectName("textEdit4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 380, 481, 31))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.inputImage.setText(_translate("Dialog", "image1"))
        self.selectImage.setText(_translate("Dialog", "select"))
        self.predictImage.setText(_translate("Dialog", "predict"))
        self.outputImage.setText(_translate("Dialog", "image2"))
        self.label.setText(_translate("Dialog", "HINT: Results are for guidance only and should not be used as a medical basis"))
