# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(502, 261)
        self.inputImage = QtWidgets.QLabel(Dialog)
        self.inputImage.setGeometry(QtCore.QRect(20, 20, 201, 171))
        self.inputImage.setObjectName("inputImage")
        self.selectImage = QtWidgets.QPushButton(Dialog)
        self.selectImage.setGeometry(QtCore.QRect(20, 220, 75, 23))
        self.selectImage.setObjectName("selectImage")
        self.predictImage = QtWidgets.QPushButton(Dialog)
        self.predictImage.setGeometry(QtCore.QRect(140, 220, 75, 23))
        self.predictImage.setObjectName("predictImage")
        self.outputImage = QtWidgets.QLabel(Dialog)
        self.outputImage.setGeometry(QtCore.QRect(290, 20, 201, 171))
        self.outputImage.setObjectName("outputImage")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(240, 210, 251, 41))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.inputImage.setText(_translate("Dialog", "image1"))
        self.selectImage.setText(_translate("Dialog", "select"))
        self.predictImage.setText(_translate("Dialog", "predict"))
        self.outputImage.setText(_translate("Dialog", "image2"))
